---

- name: Configure neutron compute agent
  ini_file:
    dest: '/etc/neutron/neutron.conf'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    # Messaging
    - section: 'DEFAULT'
      option: 'rpc_backend'
      value: 'rabbit'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_host'
      value: '{{ openstack_neutron_controller_rabbit_hostname }}'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_userid'
      value: '{{ openstack_neutron_controller_rabbit_username }}'
    - section: 'oslo_messaging_rabbit'
      option: 'rabbit_password'
      value: '{{ openstack_neutron_controller_rabbit_password }}'
    # Keystone
    - section: 'DEFAULT'
      option: 'auth_strategy'
      value: 'keystone'
    - section: keystone_authtoken
      option: identity_uri
      value: '{{ openstack_neutron_controller_keystone_protocol }}://{{ openstack_neutron_controller_keystone_hostname }}:{{ openstack_neutron_controller_keystone_admin_port }}'
    - section: keystone_authtoken
      option: auth_url
      value: '{{ openstack_neutron_controller_keystone_protocol }}://{{ openstack_neutron_controller_keystone_hostname }}:{{ openstack_neutron_controller_keystone_admin_port }}'
    - section: keystone_authtoken
      option: auth_uri
      value: '{{ openstack_neutron_controller_keystone_protocol }}://{{ openstack_neutron_controller_keystone_hostname }}:{{ openstack_neutron_controller_keystone_port }}/v3'
    - section: keystone_authtoken
      option: project_domain_name
      value: default
    - section: keystone_authtoken
      option: user_domain_name
      value: default
    - section: keystone_authtoken
      option: memcached_servers
      value: '{{ openstack_neutron_controller_keystone_hostname }}:11211'
    - section: keystone_authtoken
      option: project_name
      value: service
    - section: keystone_authtoken
      option: auth_type
      value: password
    - section: keystone_authtoken
      option: auth_version
      value: v3
    - section: keystone_authtoken
      option: username
      value: '{{ openstack_neutron_controller_neutron_user }}'
    - section: keystone_authtoken
      option: password
      value: '{{ openstack_neutron_controller_neutron_password }}'
  notify:
  - Restart linuxbridge agent

- name: Configure the Linux Bridge agent
  ini_file:
    dest: '/etc/neutron/plugins/ml2/linuxbridge_agent.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - section: 'linux_bridge'
      option: 'physical_interface_mappings'
      value: 'provider:{{ openstack_neutron_controller_provider_interface_name }}' # name of the underlying provider physical network interface (to Internet)
    - section: 'vxlan'
      option: 'enable_vxlan'
      value: 'True'
    - section: 'vxlan'
      option: 'local_ip'
      value: '{{ openstack_neutron_controller_overlay_interface_address }}' # MGMT interface
    - section: 'vxlan'
      option: 'l2_population'
      value: 'True'
    - section: 'securitygroup'
      option: 'enable_security_group'
      value: 'True'
    - section: 'securitygroup'
      option: 'firewall_driver'
      value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver'
  notify:
  - Restart linuxbridge agent
